apiVersion: v1
data:
  minio.properties: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-hms:9083
    hive.s3.aws-access-key=minioadmin
    hive.s3.aws-secret-key=minioadmin
    hive.s3.endpoint=http://minio-api.openshift-operators.svc.cluster.local:9000
    hive.s3.path-style-access=true
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: example-trino-cluster
    meta.helm.sh/release-namespace: openshift-operators
  labels:
    app: trino
    app.kubernetes.io/managed-by: Helm
    chart: trino-0.8.0
    heritage: Helm
    release: example-trino-cluster
    role: catalogs
  name: example-trino-cluster-catalog
  namespace: openshift-operators
